/**
 * Köhler's Medizinal-Pflanzen illustration mapping.
 * Maps plant slug → local illustration path (from /public/illustrations/).
 * Source: Köhler's Medizinal-Pflanzen (1887), public domain.
 *
 * 42 plants have local high-res illustrations; remaining plants
 * fall back to Wikimedia Commons Special:FilePath URLs.
 */
export const PLANT_ILLUSTRATIONS: Record<string, string> = {
  // Local illustrations (58 JPGs in /public/illustrations/)
  "arnica": "/illustrations/Arnica_montana.jpg",
  "calendula": "/illustrations/Calendula_officinalis.jpg",
  "caraway": "/illustrations/Carum_carvi.jpg",
  "cardamom": "/illustrations/Elettaria_cardamomum.jpg",
  "castor-oil": "/illustrations/Ricinus_communis.jpg",
  "cayenne-capsicum": "/illustrations/Capsicum_annuum.jpg",
  "chamomile": "/illustrations/Matricaria_chamomilla.jpg",
  "cinchona-bark": "/illustrations/Cinchona_calisaya.jpg",
  "cinnamon": "/illustrations/Cinnamomum_verum.jpg",
  "clove": "/illustrations/Syzygium_aromaticum.jpg",
  "coltsfoot": "/illustrations/Tussilago_farfara.jpg",
  "comfrey": "/illustrations/Symphytum_officinale.jpg",
  "coriander": "/illustrations/Coriandrum_sativum.jpg",
  "dandelion": "/illustrations/Taraxacum_officinale.jpg",
  "dong-quai": "/illustrations/Angelica_archangelica.jpg",
  "elder-flower": "/illustrations/Sambucus_nigra.jpg",
  "elecampane": "/illustrations/Inula_helenium.jpg",
  "eucalyptus": "/illustrations/Eucalyptus_globulus.jpg",
  "fennel": "/illustrations/Foeniculum_vulgare.jpg",
  "fenugreek": "/illustrations/Trigonella_foenum-graecum.jpg",
  "feverfew": "/illustrations/Tanacetum_parthenium.jpg",
  "gentian": "/illustrations/Gentiana_lutea.jpg",
  "ginger": "/illustrations/Zingiber_officinale.jpg",
  "goldenseal": "/illustrations/Hydrastis_canadensis.jpg",
  "hops": "/illustrations/Humulus_lupulus.jpg",
  "juniper": "/illustrations/Juniperus_communis.jpg",
  "lavender": "/illustrations/Lavandula_angustifolia.jpg",
  "lemon-balm": "/illustrations/Melissa_officinalis.jpg",
  "licorice": "/illustrations/Glycyrrhiza_glabra.jpg",
  "linden-lime-flower": "/illustrations/Tilia_cordata.jpg",
  "marshmallow": "/illustrations/Althaea_officinalis.jpg",
  "peppermint": "/illustrations/Mentha_piperita.jpg",
  "pomegranate": "/illustrations/Punica_granatum.jpg",
  "rosemary": "/illustrations/Rosmarinus_officinalis.jpg",
  "sage": "/illustrations/Salvia_officinalis.jpg",
  "senna": "/illustrations/Cassia_angustifolia.jpg",
  "st-john-s-wort": "/illustrations/Hypericum_perforatum.jpg",
  "thyme": "/illustrations/Thymus_vulgaris.jpg",
  "turmeric": "/illustrations/Curcuma_longa.jpg",
  "valerian": "/illustrations/Valeriana_officinalis.jpg",
  "witch-hazel": "/illustrations/Hamamelis_virginiana.jpg",
  "wormwood": "/illustrations/Artemisia_absinthium.jpg",
  "yarrow": "/illustrations/Achillea_millefolium.jpg",

  // Wikimedia Commons — Köhler's Medizinal-Pflanzen
  "asafoetida": "https://commons.wikimedia.org/wiki/Special:FilePath/Ferula%20assa-foetida%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-061.jpg?width=400",
  "astragalus": "https://commons.wikimedia.org/wiki/Special:FilePath/Astragalus%20brachycalyx%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-166.jpg?width=400",
  "boswellia": "https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6hler%20Boswellia.jpg?width=400",
  "coca-leaf": "https://commons.wikimedia.org/wiki/Special:FilePath/Erythroxylum%20coca%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-204.jpg?width=400",
  "corn-silk": "https://commons.wikimedia.org/wiki/Special:FilePath/Zea%20mays%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-283.jpg?width=400",
  "cumin": "https://commons.wikimedia.org/wiki/Special:FilePath/Cuminum%20cyminum%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-198.jpg?width=400",
  "lobelia": "https://commons.wikimedia.org/wiki/Special:FilePath/Lobelia%20inflata%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-218.jpg?width=400",
  "mugwort": "https://commons.wikimedia.org/wiki/Special:FilePath/Artemisia%20absinthium%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-164.jpg?width=400",
  "mullein": "https://commons.wikimedia.org/wiki/Special:FilePath/Verbascum%20phlomoides%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-144.jpg?width=400",
  "olive-leaf": "https://commons.wikimedia.org/wiki/Special:FilePath/Olea%20europaea%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-229.jpg?width=400",
  "parsley": "https://commons.wikimedia.org/wiki/Special:FilePath/Petroselinum%20crispum%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-103.jpg?width=400",
  "raspberry-leaf": "https://commons.wikimedia.org/wiki/Special:FilePath/Rubus%20idaeus%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-124.jpg?width=400",
  "saffron": "https://commons.wikimedia.org/wiki/Special:FilePath/Crocus%20sativus%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-194.jpg?width=400",
  "sweet-wormwood": "https://commons.wikimedia.org/wiki/Special:FilePath/Artemisia%20cina%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-165.jpg?width=400",
  "tea-tree-oil": "https://commons.wikimedia.org/wiki/Special:FilePath/Melaleuca%20leucadendra%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-092.jpg?width=400",

  // Wikimedia Commons — Thomé's Flora von Deutschland & other Flora illustrations
  "bilberry": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Vaccinium%20myrrtillus0.jpg?width=400",
  "blessed-thistle": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Cnicus%20benedictus0.jpg?width=400",
  "butcher-s-broom": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Ruscus%20aculeatus%20clean.jpg?width=400",
  "butterbur": "https://commons.wikimedia.org/wiki/Special:FilePath/Petasites%20hybridus%20Thome%20DESC.JPG?width=400",
  "cayenne": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Capsicum%20annuum0.jpg?width=400",
  "chicory": "https://commons.wikimedia.org/wiki/Special:FilePath/Cichorium%20intybus%20Thome%20DESC.jpg?width=400",
  "cramp-bark": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Viburnum%20opulus%20clean.JPG?width=400",
  "ephedra": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Ephedra%20distachya1.jpg?width=400",
  "eyebright": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Euphrasia%20rostkoviana0.jpg?width=400",
  "goldenrod": "https://commons.wikimedia.org/wiki/Special:FilePath/Solidago%20virgaurea%20ssp%20virgaurea.jpg?width=400",
  "hawthorn": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Crataegus%20laevigata1.jpg?width=400",
  "horse-chestnut": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Aesculus%20hippocastanum0%20clean.jpg?width=400",
  "ivy-leaf": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Hedera%20helix0.jpg?width=400",
  "lady-s-mantle": "https://commons.wikimedia.org/wiki/Special:FilePath/Alchemilla%20vulgaris%20%28Thom%C3%A9%20Bd.3%201905%2C%20BHL-81509%2C%20Tafel%20338%29%20clean.jpg?width=400",
  "milk-thistle": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Silybum%20marianum0.jpg?width=400",
  "oatmeal": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Avena%20sativa0.jpg?width=400",
  "onion": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Allium%20schoenoprasum%20and%20Allium%20cepa0%20clean.jpg?width=400",
  "plantain": "https://commons.wikimedia.org/wiki/Special:FilePath/Plantago%20mjor%20Thome%20DESC.png?width=400",
  "red-clover": "https://commons.wikimedia.org/wiki/Special:FilePath/Trifolium%20pratense%20%28Thom%C3%A9%20Bd.3%201905%2C%20BHL-81509%2C%20Tafel%20357%29%20clean.jpg?width=400",
  "shepherd-s-purse": "https://commons.wikimedia.org/wiki/Special:FilePath/Capsella%20bursa-pastoris%20%28Flora%20of%20Tajikistan%29.png?width=400",
  "stinging-nettle": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Urtica%20dioica0%20clean.jpg?width=400",
  "uva-ursi": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20Arctostaphylos%20uva-ursi0.jpg?width=400",
  "white-willow-bark": "https://commons.wikimedia.org/wiki/Special:FilePath/Thom%C3%A9%20Salix%20alba%20clean.jpg?width=400",

  // Wikimedia Commons — Other public domain botanical illustrations
  "aloe-vera": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20from%20Medical%20Botany%2C%20digitally%20enhanced%20from%20rawpixel%27s%20own%20original%20plates%20173.jpg?width=400",
  "california-poppy": "https://commons.wikimedia.org/wiki/Special:FilePath/Eschscholzia%20californica%20illustration%20valentien.jpg?width=400",
  "echinacea": "https://commons.wikimedia.org/wiki/Special:FilePath/Addisonia%20-%20colored%20illustrations%20and%20popular%20descriptions%20of%20plants%20%281916-%281964%29%29%20%2816585225938%29.jpg?width=400",
  "garlic": "https://commons.wikimedia.org/wiki/Special:FilePath/Mother%20Earth%27s%20Children%20p.50.jpg?width=400",
  "horseradish": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustration%20from%20Medical%20Botany%2C%20digitally%20enhanced%20from%20rawpixel%27s%20own%20original%20plates%20154.jpg?width=400",
  "neem": "https://commons.wikimedia.org/wiki/Special:FilePath/Margosa%20%28Azadirachta%20indica%20A.%20Juss.%29%3B%20branch%20with%20flowers%20a%20Wellcome%20V0042617.jpg?width=400",
  "papaya": "https://commons.wikimedia.org/wiki/Special:FilePath/Illustrations%20of%20Indian%20Botany%2C%20Vol.%202%20%28page%2081%20crop%29.jpg?width=400",
  "rauwolfia": "https://commons.wikimedia.org/wiki/Special:FilePath/Indian%20Snakeroot%20or%20Java%20Devilpepper%20%28Rauvolfia%20serpentina%20%28%20Wellcome%20V0042670.jpg?width=400",

  // Supplementary plants — public domain botanical illustrations
  "black-seed": "https://commons.wikimedia.org/wiki/Special:FilePath/Nigella%20sativa%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-227.jpg?width=400",
  "amla": "https://commons.wikimedia.org/wiki/Special:FilePath/Phyllanthus%20emblica%20Bra52.png?width=400",
  "guduchi": "https://commons.wikimedia.org/wiki/Special:FilePath/Indian%20Medicinal%20Plants%20-%20Plate%2035%20-%20Tinospora%20cordifolia.jpg?width=400",
  "burdock": "https://commons.wikimedia.org/wiki/Special:FilePath/Arctium%20lappa%20botanilac%20illustration.jpg?width=400",
  "he-shou-wu": "https://commons.wikimedia.org/wiki/Special:FilePath/%E6%A4%8D%E7%89%A9%E5%90%8D%E5%AF%A6%E5%9C%96%E8%80%83%C2%B7%E4%BD%95%E9%A6%96%E7%83%8F.jpg?width=400",
  "tamarind": "https://commons.wikimedia.org/wiki/Special:FilePath/Tamarindus%20indica%20-%20K%C3%B6hler%E2%80%93s%20Medizinal-Pflanzen-134.jpg?width=400",
  "moringa": "https://commons.wikimedia.org/wiki/Special:FilePath/Moringa%20oleifera%20Blanco1.125.png?width=400",
  "wild-yam": "https://commons.wikimedia.org/wiki/Special:FilePath/NIE%20Yam%20-%20Dioscorea%20villosa.jpg?width=400",
  "tribulus": "https://commons.wikimedia.org/wiki/Special:FilePath/Tribulus%20terrestris.svg?width=400",
  "arjuna": "https://commons.wikimedia.org/wiki/Special:FilePath/Terminalia%20arjuna%20Govindoo.jpg?width=400",
};
